### ISSUE TITLE
Timeline for Vue 3

### ISSUE THREAD

**Issue by TheCelebrimbor** [mdbootstrap/mdb4-vue-ui-kit#1]
Hi!, do we have a timeline for vue3 support with BS5 (All components) ?

**Comment by smolenski-mikolaj** [comment]
Hi, here's current roadmap: https://mdbootstrap.com/docs/b5/roadmap/

There is a chance for a stable version of MDB5 Vue Pro Essential  in July. Llater we will work on the Advanced version.

Keep coding,
Mikołaj from MDB
