### ISSUE TITLE
Any chance you can publish @types/mdb-vue-ui-kit so that TypeScript doesn't choke in development?

### ISSUE THREAD

**Issue by kbottner** [mdbootstrap/mdb4-vue-ui-kit#2]
**Issue**
``` javascript
import { MDBCarousel } from "mdb-vue-ui-kit";
```
Causes the following error:
> TS7016: Could not find a declaration file for module 'mdb-vue-ui-kit'. 'D:/dev/testprj/node_modules/mdb-vue-ui-kit/js/mdb.umd.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/mdb-vue-ui-kit` if it exists or add a new declaration (.d.ts) file containing `declare module 'mdb-vue-ui-kit';`
``` javascript
    10 | <script lang="ts">
    11 | import { defineComponent, ref } from "vue";
  > 12 | import { MDBCarousel } from "mdb-vue-ui-kit";
       |                             ^^^^^^^^^^^^^^^^
```

I am using Vue3 with Typescript. I believe the addition of the @types/mdb-vue-ui-kit will clear this up.

**Comment by smolenski-mikolaj** [comment]
Thanks for posting this request. We will check possible options soon.

**Comment by kbottner** [comment]
Question what kind of donation would make this a top priority?

**Comment by smolenski-mikolaj** [comment]
We've just released types yesterday. Please check the latest version.

Keep coding, 
Mikołaj from MDB
