### ISSUE TITLE
ViteJs

### ISSUE THREAD

**Issue by folamy** [mdbootstrap/mdb4-vue-ui-kit#3]
Is there any plan for ViteJS support?

**Comment by smolenski-mikolaj** [comment]
Yes, we're going to integrate UI KIT with ViteJS in Q3 2021.

**Comment by folamy** [comment]
That would be awesome! And Hopefully, SSR would be in consideration.

**Comment by smolenski-mikolaj** [comment]
Hi there, we've made a new tutorial for MDB Vue integration with Vite.
https://mdbootstrap.com/docs/b5/vue/getting-started/installation/#section-vite

Keep coding, 
Mikołaj from MDB
