### ISSUE TITLE
MDBTabs doesn't change active Tab id

### ISSUE THREAD

**Issue by mehdinourollah** [mdbootstrap/mdb4-vue-ui-kit#5]
I used Tabs like this
```vue
<MDBTabs v-model="selectedTabIndexData">
    <MDBTabItem>Titles</MDBTabItem>
    ...
   
<MDBTabContent>
   <MDBTabPane>Contents...
``` 
And I need to change the active tab by changing the selectedTabIndexData ( triggering the v-model). But No matter of what It doesn't change the Active Tab

**Comment by smolenski-mikolaj** [comment]
Thanks for your remarks! We're going to fix it soon.

Keep coding, 
Mikołaj from MDB

**Comment by kbottner** [comment]
I am having a similar problem, though in my case the tab content isn't showing up at all.

It appears that the content for each has the `style="display:none;"` set and neither clicking on a tab nor changing the value programmatically changes the value keeping all content essentially hidden.

**Comment by smolenski-mikolaj** [comment]
The issue has been solved in the latest release.

Keep coding, 
Mikołaj from MDB
