### ISSUE TITLE
Question about PRO version timeline

### ISSUE THREAD

**Issue by kbottner** [mdbootstrap/mdb4-vue-ui-kit#6]
I was just wondering if there is a timeline for the PRO version. I would certainly like to purchase a PRO version for all the additional features but don't want to buy it now because this MDB version for Vue doesn't have them. Do you have a timeline on when the PRO version will be available? Or should I buy the PRO version now and use the PRO straight javascript for the components that have not been ported to MDB yet?

Thanks in advance

**Comment by smolenski-mikolaj** [comment]
The most likely release date for the PRO ESSENTIAL version is Q3. 

Keep coding, 
Mikołaj from MDB
